### ISSUE TITLE
ch2 test error: `TypeError: socket.respond_200() missing 1 required positional argument: 'response_body'`

### ISSUE THREAD

**Issue by bzy-debug** [cs4560-utah-sp24/test#21]
python version: 3.12.5

```
$ python3 test/run.py ch2-line-breaks
**********************************************************************
File "/Users/bzy/Workspace/browserengineering/test/ch02/ex-line-breaks.md", line 38, in ex-line-breaks.md

    Let's mock a URL to load:

    >>> url = 'http://wbemocks.test/chapter2-example3'
    >>> wbemocks.socket.respond_200(url=url,
    ...   body=("u\n" +
    ...         "d"))

Expected nothing
Got nothing
Exception Raised:
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/doctest.py", line 1368, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest ex-line-breaks.md[7]>", line 1, in <module>
        wbemocks.socket.respond_200(url=url,
    TypeError: socket.respond_200() missing 1 required positional argument: 'response_body'
**********************************************************************
1 items had failures:
   4 of   7 in ex-line-breaks.md
***Test Failed*** 4 failures.
```

python panics that `socket.respond_200` is missing argument `response_body`, this function is defined at https://github.com/cs4560-utah-sp24/test/blob/main/tests/wbemocks.py#L161 **with** a parameter named `response_body`

**Comment by bzy-debug** [comment]
After I change `body` to `response_body`, there's another error:

```
Exception Raised:
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/doctest.py", line 1368, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest ex-line-breaks.md[9]>", line 1, in <module>
        this_browser.load(browser.URL(url))
      File "/Users/bzy/Workspace/browserengineering/browser.py", line 203, in load
        self.draw()
      File "/Users/bzy/Workspace/browserengineering/browser.py", line 210, in draw
        self.canvas.create_text(x, y - self.scroll, text=c)
      File "/Users/bzy/Workspace/browserengineering/test/tests/wbemocks.py", line 473, in create_text
        y2 = y + font.metrics("linespace")
                 ^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'metrics'
```

I have to comment line 473 and line 474 to make it not throw exception

**Comment by bzy-debug** [comment]
After comment the two lines I still cannot pass the test.

I have to change `create_text` into this:

```python
    def create_text(self, x, y, text, font=None, anchor=None, fill=None):
        if text.isspace(): return
        if font or anchor:
            cmd = "create_text: x={} y={} text={} font={} anchor={}".format(
                x, y, text, font, anchor)
        else:
            cmd = "create_text: x={} y={} text={}".format(x, y, text)
        print(cmd) # add this line
        self._draw(cmd)
        # y2 = y + font.metrics("linespace")
        # if self._allow("create_text", y2): print(cmd)
```

to pass test.

I think the `self._draw` should print to stdout?

**Comment by ljweel** [comment]
Thank you, I've seen this and solved the same issue.
